[book]
# 作者
authors = ["henry_23"]
# 标题
title = "mdBook 模板"
language = "zh-Hans"
# "zh-Hans": Simplified Chinese
# "zh-Hant": Traditional Chinese
multilingual = false
src = "src"

[output.html]
additional-css = ["theme/css/custom-style.css", "theme/css/custom-font.css"]
# Git 仓库链接
git-repository-url = "https://github.com/tsagaanbar/mdbook-template"
# 编辑链接模板
edit-url-template = "https://github.com/tsagaanbar/mdbook-template/edit/main/{path}"
# MathJax 支持
mathjax-support = true
